server:
 port: 8880
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/shop?currentSchema=auth-srv
  username: psqluser
  password: Password123
  hikari:
    max-lifetime: 600000
 jpa:
  properties:
   hibernate:
    jdbc:
     lob:
      non_contextual_creation: true
 security:
  oauth2:
   client:
    pre-established-redirect-uri: http://eureka-shop-service:8189/login
    registered-redirect-uri: http://eureka-shop-service:8189/login
    use-current-uri: false