server:
 port: 8880
spring:
 jpa:
  properties:
   hibernate:
    jdbc:
     lob:
      non_contextual_creation: true
 security:
  oauth2:
   client:
    pre-established-redirect-uri: http://eureka-shop-service:8189/login
    registered-redirect-uri: http://eureka-shop-service:8189/login
    use-current-uri: false