server:
 port: 9545
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://165.22.76.72:5432/shop?currentSchema=products
  username: psqluser
  password: Password123
  hikari:
    max-lifetime: 600000
 jpa:
  properties:
   hibernate:
    jdbc:
     lob:
      non_contextual_creation: true
security:
  oauth2:
    resource:
      userInfoUri: http://localhost:8880/user
    client:
      client-id: secureClientToken
      client-secret: verySecretWord

