server:
 port: 8880
security
 oauth2:
  client:
   registered-redirect-uri: http://eureka-shop-service:8189/login
   use-current-uri: false
spring:
 datasource:
  driver-class-name: org.postgresql.Driver
  url: jdbc:postgresql://165.22.76.72:5432/shop?currentSchema=auth-srv
  username: psqluser
  password: Password123
  hikari:
    max-lifetime: 600000
 jpa:
  properties:
   hibernate:
    jdbc:
     lob:
      non_contextual_creation: true